<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/RETAIL/Schema.xsd" xmlns:tns="http://xmlns.example.com/1541446260400" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1541446260400">
    <import namespace="http://www.tibco.com/schemas/RETAIL/Schema.xsd" location="../SCHEMAS/Schema.xsd"/>
    <message name="INPUT">
        <part name="COMPANY" type="xsd:string"/>
    </message>
    <message name="OUTPUT">
        <part name="OUTPUT" element="ns:RETAIL"/>
    </message>
    <message name="ERROR">
        <part name="ERROR" type="xsd:string"/>
    </message>
    <portType name="PortType">
        <operation name="Operation">
            <input message="tns:INPUT"/>
            <output message="tns:OUTPUT"/>
            <fault name="fault1" message="tns:ERROR"/>
        </operation>
    </portType>
</definitions>