<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.example.org/schema/1549340414918" xmlns:tns="http://www.example.org/wsdl/1549340414560" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Rank" targetNamespace="http://www.example.org/wsdl/1549340414560">
  <wsdl:import namespace="http://www.example.org/schema/1549340414918"/>
  <wsdl:message name="operationRequest">
    <wsdl:part element="extns:Request_Operation" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="operationResponse">
    <wsdl:part element="extns:Response_Operation" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="operationFault">
    <wsdl:part element="extns:Fault_Operation" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Rank">
    <wsdl:operation name="operation">
      <wsdl:input message="tns:operationRequest" name="operationInput"/>
      <wsdl:output message="tns:operationResponse" name="operationOutput"/>
      <wsdl:fault message="tns:operationFault" name="Fault"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
