<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/BOS/Schemas/Schema.xsd" xmlns:tns="http://xmlns.example.com/1541298402201" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1541298402201">
    <import namespace="http://www.tibco.com/schemas/BOS/Schemas/Schema.xsd" location="../Schemas/Schema.xsd"/>
    <message name="Input">
        <part name="Account_No" type="xsd:string"/>
    </message>
    <message name="Output">
        <part name="Output" element="ns:BOS"/>
    </message>
    <message name="Error">
        <part name="Error" type="xsd:string"/>
    </message>
    <portType name="PortType">
        <operation name="Operation">
            <input message="tns:Input"/>
            <output message="tns:Output"/>
            <fault name="fault1" message="tns:Error"/>
        </operation>
    </portType>
</definitions>